wingkwong/leetcode-the-hard-way

tutorials/graph-theory/README.md
tutorials/graph-theory/depth-first-search.md
tutorials/graph-theory/introduction.md

I have attempted to use a more straightforward form of writing. 
I have updated content in Graph:
-Introduction
-DFS

Content Updated: Graph Introduction and DFS 

---

tutorials/graph-theory/breadth-first-search.md
tutorials/graph-theory/depth-first-search.md

Added problems for DFS
Added two examples for BFS

GitBook: [#3] No subject

---

solutions/0400-0499/0404-sum-of-left-leaves-easy.md
solutions/0500-0599/0559-maximum-depth-of-n-ary-tree-easy.md
tutorials/graph-theory/breadth-first-search.md

Provided solution to problem 404 and 559

Updated Problem 404, 559 and added problems to BFS

---

solutions/0400-0499/0402-remove-k-digits-medium.md

Added 0402-remove-k-digits [medium] solution

---

tutorials/basic-topics/heap.md

added c++ tutorial in heap.md with a leetcode example.

upload c++ tutorial of heap

---

tutorials/basic-topics/heap.md

1. Added my name
2. The headings of deletion and insertion do not match, so I fixed it now
Please have a look thanks

Update and fixed heap.md markdown

---

solutions/0000-0099/0001-two-sum.md
solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md
solutions/0000-0099/0005-longest-palindromic-substring-medium.md
solutions/0000-0099/0009-palindrome-number-easy.md
solutions/0000-0099/0011-container-with-most-water-medium.md
solutions/0000-0099/0021-merge-two-sorted-lists-easy.md
solutions/0000-0099/0023-merge-k-sorted-lists-hard.md
solutions/0000-0099/0024-swap-nodes-in-pairs-medium.md
solutions/0000-0099/0028-implement-strstr-easy.md

added java solutions from 1 to 28 problems and fixed Tab view of each problem from 1 to 28 problems

Added Java Solution and Fixed Bug Fix Of Tab View

---

solutions/0000-0099/0034-find-first-and-last-position-of-element-in-sorted-array-medium.md
solutions/0000-0099/0035-search-insert-position-easy.md
solutions/0000-0099/0048-rotate-image-medium.md
solutions/0000-0099/0062-unique-paths-medium.md

Added Java Solutions

---

tutorials/graph-theory/breadth-first-search.md

Updated the problem link in breadth-first-search.md file.

Updated the problem link

---

solutions/0000-0099/0094-binary-tree-inorder-traversal-easy.md

added java solution to question 94

added java solution

---

solutions/0100-0199/0113-path-sum-ii-medium.md
solutions/0400-0499/0429-n-ary-tree-level-order-traversal-medium.md
solutions/0900-0999/0987-vertical-order-traversal-of-a-binary-tree-hard.md

added C# Solution

---

tutorials/graph-theory/binary-tree.md

Adding some properties in binary tree and correcting a typo

adding properties

---

solutions/0100-0199/0113-path-sum-ii-medium.md
solutions/0100-0199/0141-linked-list-cycle.md
solutions/0400-0499/0429-n-ary-tree-level-order-traversal-medium.md
solutions/0600-0699/0606-construct-string-from-binary-tree-easy.md
solutions/0900-0999/0987-vertical-order-traversal-of-a-binary-tree-hard.md
solutions/2400-2499/2418-sort-the-people-easy.md

fixed C# language markdown highlights
added C# solutions

fixed C# language markdown highlights &  added C# solutions

---

tutorials/graph-theory/disjoint-set-union.md

These are the problems that one should definitely give a try.
You might upload solution of these problems (which will be great if you do).
I don't know why but I was not able to make the table. Sorry :(

Added some good Problems related to DSU

---

solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

Clean and concise solution with one loop. Please check if this is good to merge..

Modified clean & concise solution with One Loop

---

tutorials/math/bit-manipulation.md

I have modified Bit Manipulation Tutorials, Please take a look if this is good to go.

Bit manipulation

---

solutions/0000-0099/0007-reverse-integer-medium.md

Added Reverse Integer solution, please check if this is good to go.

Reverse Integer medium solution

---

solutions/0000-0099/0005-longest-palindromic-substring-medium.md

Added HashSet and ASCII based approach, please take a look if this good to merge.

0005-Longest Palindrome added 2 other approaches

---

solutions/0000-0099/0034-find-first-and-last-position-of-element-in-sorted-array-medium.md

Instead of having two loops for start and end index, combined with one loop and added a condition if Start index is not found, then not check end index (because it won't be in the array)

Changed solution with the optimal approach

---

solutions/0000-0099/0036-valid-sudoku-easy.md

Added Valid Sudoku solution, Description was not added through converter, it's directly added, Take a look if it's good to merge.

Valid Sudoku Leetcode solution

---

solutions/0000-0099/0033-search-in-rotated-sorted-array-medium.md

0033-search-in-rotated-sorted-array solution added, please check if this is good to go.

Search in rotated array binary search solution

---

tutorials/math/bit-manipulation.md

Few places binary numbers display not correct, just updated. Please take a look if this is good to go.

Formatting changes on binary numbers display

---

solutions/0000-0099/0014-longest-common-prefix-easy.md

Longest common prefix solution added. Please check if this good to go.

solution: 0014-longest-common-prefix added

---

solutions/0000-0099/0019-remove-nth-node-from-end-of-list-medium.md

Problem image link added, Please check if this is Ok.

solution: 0019-remove-nth-node-from-end-of-list

---

solutions/0000-0099/0020-valid-parentheses-easy.md

Valid Parentheses solution added, check if this is Ok

solution: 0020 valid parentheses created

---

solutions/0700-0799/0706-design-hashmap-medium.md
tutorials/basic-topics/hash-map.md

Design HashMap solution and added a link in HashMap tutorials.

solutions: 0706-design-hashmap solution

---

solutions/0700-0799/0706-design-hashmap-medium.md

LaTeX update for numbers display.

0706 design hashmap

---

solutions/0000-0099/0037-sudoku-solver-hard.md

Tried best to explain, let me know if any changes needed.

0037 sudoku solver

---

tutorials/dynamic-programming.md

Hope I explained it well, let me know if you need anything changed.

Added write-up on Dynamic Programming.

---

solutions/0100-0199/0125-valid-palindrome.md

The purpose of this PR is to add my solution to the `Valid Palindrome` Leetcode problem which can be found [here](https://leetcode.com/problems/valid-palindrome/).

Adding 125 Valid palindrome in Python

---

solutions/0000-0099/0017-letter-combinations-of-a-phone-number-medium.md

Letter combination of a phone number solution added, let me know if any changes needed.

solution: 0017-letter-combinations-of-a-phone-number added

---

solutions/1500-1599/1588-sum-of-all-odd-length-subarrays-easy.md

Adds Java solution for 1588. Three different approaches with time and space analysis.

add solution for 1588 - Sum Of All Odd Length Subarrays (easy)

---

solutions/2400-2499/2413-smallest-even-multiple-easy.md

Add solution for 2413-smallest-even-multiple-easy

Add solution for 2413-smallest-even-multiple-easy (Java)

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

Merge Sorted Array (Easy) solved using two approaches(brute force[sorting] and two pointers) in java

adding solution: 0088  Merge Sorted Array, codes written in java

---

solutions/0100-0199/0191-number-of-1-bits-easy.md

solution: 0191-number-of-1-bits

solution: 0191-number-of-1-bits

---

solutions/0100-0199/0104-maximum-depth-of-binary-tree-easy.md

solution: 0104-maximum-depth-of-binary-tree

solution: 0104-maximum-depth-of-binary-tree

---

solutions/0100-0199/0136-single-number-easy.md

solution: 0136-single-number updated with java solution

solution: 0136-single-number updated with java solution

---

solutions/0100-0199/0141-linked-list-cycle.md

solution: 0141-linked-list-cycle updated with java solution

solution: 0141-linked-list-cycle updated with java solution

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

solution: 0144-binary-tree-preorder-traversal iterative solution added

solution: 0144-binary-tree-preorder-traversal iterative solution added

---

solutions/0100-0199/0145-binary-tree-postorder-traversal-easy.md

solution: 0145-binary-tree-postorder-traversal iterative solution added

solution: 0145-binary-tree-postorder-traversal iterative solution added

---

solutions/0200-0299/0200-number-of-islands-medium.md

solution: 0200-number-of-islands updated with java solution

solution: 0200-number-of-islands updated with java solution

---

solutions/0100-0199/0148-sort-list-medium.md

Solution added for 0148-sort-list, Please check if this is Ok.

0148-sort-list

---

solutions/0200-0299/0205-isomorphic-strings-easy.md

solution: 0205-isomorphic-strings updated with java solution

solution: 0205-isomorphic-strings updated with java solution

---

solutions/0200-0299/0202-happy-number-easy.md

solution: 0202-happy-number updated with java solution

solution: 0202-happy-number updated with java solution

---

solutions/0200-0299/0217-contains-duplicate-easy.md

solution: 0217-contains-duplicate updated with java solution

solution: 0217-contains-duplicate updated with java solution

---

solutions/0200-0299/0268-missing-number-easy.md

solution: 0268-missing-number updated with java solutions

solution: 0268-missing-number updated with java solutions

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

solution: 0088-merge-sorted-array updated optimal approach

solution: 0088-merge-sorted-array updated optimal approach

---

solutions/0200-0299/0242-valid-anagram-easy.md

solution: 0242-valid-anagram updated with java solutions

solution: 0242-valid-anagram updated with java solutions

---

solutions/0200-0299/0234-palindrome-linked-list-easy.md

solution: 0234-palindrome-linked-list updated with java solutions

solution: 0234-palindrome-linked-list updated with java solutions

---

solutions/0200-0299/0231-power-of-two-easy.md

solution: 0231-power-of-two updated with java solution

solution: 0231-power-of-two updated with java solution

---

solutions/0000-0099/0078-subsets-medium.md

solution: 0078-subsets java solution added

solution: 0078-subsets

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

solution: 0144-binary-tree-preorder-traversal **typos fix**

solution: 0144-binary-tree-preorder-traversal typos fix

---

solutions/0000-0099/0094-binary-tree-inorder-traversal-easy.md

solution: 0094-binary-tree-inorder-traversal iterative solution added

solution: 0094-binary-tree-inorder-traversal iterative solution added

---

solutions/0100-0199/0101-symmetric-tree-easy.md

solution: 0101-symmetric-tree updated with java solution

solution: 0101-symmetric-tree updated with java solution

---

solutions/0000-0099/0076-minimum-window-substring-hard.md

solution: 0076-minimum-window-substring

---

collections/index.md

Updating collections introductions page

---

solutions/0200-0299/0283-move-zeroes-easy.md

solution: 0283-move-zeros updated with java solutions

solution: 0283-move-zeros updated with java solutions

---

solutions/0300-0399/0392-is-subsequence-easy.md

solution: 0392-is-subsequence updated with java solution

---

solutions/0000-0099/0001-two-sum.md

This is not a issue but increased more language options for website.

Added two sum javascript solution

---

solutions/0300-0399/0392-is-subsequence-easy.md

Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary.
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution: 0392-is-subsequence DP Memoization added

---

tutorials/basic-topics/sorting/merge-sort.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

merge-sort intentation formatting changes

---

solutions/1500-1599/1514-path-with-maximum-probability.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution : 1514-path-with-maximum-probability added #183

---

solutions/0900-0999/0912-sort-an-array-medium.md
solutions/2100-2199/2161-partition-array-according-to-given-pivot-medium.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

fixed typo in problem number and added java solution

---

solutions/0000-0099/0001-two-sum.md
solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

Javascript solution for Longest Substring Without Repeating Characters
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Javascript solution for Longest Substring Without Repeating Characters

---

solutions/1500-1599/1588-sum-of-all-odd-length-subarrays-easy.md
tutorials/basic-topics/sorting/selection-sort.md

Added selection sort per issue #96

Add selection sort algorithm

---

solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution: 2302-count-subarrays-with-score-less-than-K added

---

solutions/0400-0499/0445-Add-Two-Numbers-II.md
solutions/0400-0499/445-Add-Two-Numbers-ll.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution: 0445-Add-Two-Numbers-II added

---

solutions/0400-0499/0445-Add-Two-Numbers-II.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution: 0445-add-two-numbers-ii stack solution

---

solutions/0600-0699/0623-add-one-row-to-tree-medium.md

Done all the changes suggested with proper formatting and LaTex
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added Solution #0623

---

CONTRIBUTING.md

line 62 : "Appy LaTeX" => "Use LaTeX".

correct typo/wording in contributing.md

---

tutorials/basic-topics/linear-search.md

Fixes issue #126 
Added tutorial for linear search.
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added tutorial for linear search | Issue number #126

---

tutorials/math/combinatorics.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added tutorial for Combinatorics (Issue #68)

---

tutorials/basic-topics/linked-list.md

Complete linked list tutorial. 
- [x ] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x ] Make sure you've followed the template format
- [ x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x ] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [ x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`) …

Linked list tut

---

solutions/0000-0099/0009-palindrome-number-easy.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

solution: 0009-palindrome-number JS changes

---

solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md

Added the solution of the leetcode problem 102 with preferable changes
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added the solution of problem 0102, with preferable changes

---

solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

added_leet_code_1590

---

solutions/0100-0199/0125-valid-palindrome.md

The purpose of this PR is to add the `C++`, `Java`, and `JavaScript` solutions for the [0125 - Valid Palindrome](https://leetcode.com/problems/valid-palindrome/) LeetCode problem.

Added solutions for C++, Java, & JavaScript - 0125 - valid palindrome

---

solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added javascript solution in approach-2 0003-longest-substring-without-repeating-characters-medium.md

---

solutions/0000-0099/0020-valid-parentheses-easy.md

The purpose of this PR is to add three coding solutions in`C++`, `JavaScript`, and `Python` for the LeetCode [Valid Parentheses](https://leetcode.com/problems/valid-parentheses/) problem.
- [-] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
```` …

Added C++, JavaScript, and Python solution for Valid Parentheses

---

tutorials/graph-theory/tarjans-algorithm.md

Added Tutorial for Tarjan's algorithm

Added tutorial for Tarjan's Algorithm

---

solutions/0000-0099/0023-merge-k-sorted-lists-hard.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

added solution for problem 23

---

solutions/0400-0499/0403-Frog-Jump.md

````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added 0403-Frog-Jump.md

---

solutions/0000-0099/0013-roman-to-integer-easy.md

Create file for solution 0013 - Roman to Integer (easy)
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Add Solution 0013 - Roman to Integer (easy)

---

solutions/0000-0099/0070-climbing-stairs-easy.md

Added Solution: 0070-climbing-stairs-easy

---

solutions/1900-1999/1916-count-ways-to-build-rooms-in-an-ant-colony.md
tutorials/math/combinatorics.md

Added Combinatorics solution for Problem 1916 - Count Ways to Build Rooms in an Ant Colony in C++. This was one of the practice problems for my Combinatorics tutorial, and thus, I have also added a link to the same in my tutorial.

Added solution for Problem 1916 - Count Ways to Build Rooms in an Ant Colony

---

solutions/0000-0099/0001-two-sum.md

Added a new approach to solve the 0001-two-sum.md problem.
````
<Tabs>
```cpp
```
</TabItem>
</Tabs>
````

Added new approach to 0001-two-sum.md

---

solutions/0600-0699/0692-top-k-frequent-words-medium.md

solution: 0692-top-k-frequent-words solution added

---

solutions/0200-0299/0208-implement-trie-medium.md

0208 implement trie

---

solutions/0000-0099/0048-rotate-image-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Rotate Image](https://leetcode.com/problems/rotate-image/) problem.

Added Python solution for 0048 - Rotate Image.

---

solutions/0000-0099/0011-container-with-most-water-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Container With Most Water](https://leetcode.com/problems/container-with-most-water/) problem.

Added Python Solution for 0011 - Container With Most Water.

---

solutions/0000-0099/0094-binary-tree-inorder-traversal-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) problem.

Added Python Solution for 0094 - Binary Tree Inorder Traversal.

---

solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Longest Substring Without Repeating Character](https://leetcode.com/problems/longest-substring-without-repeating-characters/) problem.

Added Python solution for 0003 - Longest Substring Without Repeating Character.

---

solutions/2200-2299/2260-minimum-consecutive-cards-to-pick-up-medium.md

added python solution for leetcode 2260

---

solutions/2200-2299/2260-minimum-consecutive-cards-to-pick-up-medium.md
solutions/2400-2499/2441-largest-positive-integer-that-exists-with-its-negative-easy.md

added python solution for leetcode 244 .

added python solution for leetcode 244

---

solutions/0000-0099/0023-merge-k-sorted-lists-hard.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Merge K Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists/) problem.

Added Solution in Python for 0023 - Merge K Sorted Lists.

---

solutions/0400-0499/0417-pacific-atlantic-water-flow-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Pacific Atlantic Water Flow](https://leetcode.com/problems/pacific-atlantic-water-flow/) problem.

Added Python solution for 0417 - Pacific Atlantic Water Flow.

---

solutions/2200-2299/2232-minimize-result-by-adding-parentheses-to-expression-medium.md

Added a solution with explanation for 2232

added solution for 2232

---

solutions/0200-0299/0206-reverse-linked-list-easy.md

The purpose of this PR is to add coding solutions (Iterative and Recursive) in Python for the LeetCode [Reverse Linked List](https://leetcode.com/problems/reverse-linked-list/) problem.

Added Python solutions for 0206 - Reverse Linked List.

---

solutions/0200-0299/0234-palindrome-linked-list-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/) problem.

Added Python solution for 0234 - Palindrome Linked List.

---

solutions/0000-0099/0098-validate-binary-search-tree-medium.md

0098 validate binary search tree

---

solutions/0700-0799/0733-flood-fill-easy.md

solution: 0733-flood-fill java solution added

---

solutions/0300-0399/0345-reverse-vowels-of-a-string-easy.md

solution: 0345-reverse-vowels isVowel switch expression

---

solutions/0300-0399/0344-reverse-string-easy.md

solution: 0344-reverse-string java solution added

---

solutions/0000-0099/0021-merge-two-sorted-lists-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/) problem.

Added Python solution for 0021 - Merge Two Sorted Lists.

---

solutions/0000-0099/0024-swap-nodes-in-pairs-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs/) problem.

Added Python solution for 0024 - Swap Nodes in Pairs.

---

solutions/0000-0099/0033-search-in-rotated-sorted-array-medium.md

The purpose of this PR is to add coding solution and approach in Python for the LeetCode [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/) problem.

Added Python approach and solution for 0033 - Search in Rotated Sorted Array.

---

solutions/0000-0099/0035-search-insert-position-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Search Insert Position](https://leetcode.com/problems/search-insert-position/) problem.

Added Python solution for 0035 - Search Insert Position.

---

solutions/0200-0299/0299-bulls-and-cows-medium.md
solutions/1900-1999/1992-find-all-groups-of-farmland-medium.md

added 2 leetcode solutions in python

---

solutions/0000-0099/0042-trapping-rain-water-hard.md

Python solution for leetcode 42 - Trapping Rain Water, under approach 3, monotonic stack.

Leetcode 0042 Approach 3 Python Solution

---

solutions/0500-0599/0572-subtree-of-another-tree-easy.md

solution: 0572 subtree of another tree added

---

solutions/0000-0099/0036-valid-sudoku-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Valid Sudoku](https://leetcode.com/problems/valid-sudoku/) problem.

Added Python solution for 0036 - Valid Sudoku.

---

solutions/0000-0099/0039-combination-sum-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Combination Sum](https://leetcode.com/problems/combination-sum/) problem.

Added Python solution for 0039 - Combination Sum.

---

solutions/0000-0099/0046-permutations-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Permutation](https://leetcode.com/problems/permutations/) problem.

Added Python solution for 0046 - Permutation.

---

solutions/0400-0499/0424-longest-repeating-character-replacement-medium.md

Created .md file for question 0424 and added 2 python approaches.

Created 0424 and added 2 python approaches.

---

solutions/0000-0099/0049-group-anagrams-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Group Anagrams](https://leetcode.com/problems/group-anagrams/) problem.

Added Python solution for 0049 - Group Anagrams.

---

solutions/0500-0599/0567-permutation-in-string-medium.md

Added a slightly different second approach to leetcode 0567, and made the required changes to support the template.

Added Approach 2, using Python to 0567

---

solutions/0000-0099/0076-minimum-window-substring-hard.md

0076 Python solution for approach 1

0076 python solution for approach 1

---

solutions/0200-0299/0239-sliding-maximum-window-hard.md

Created 0239 and added 2 approaches.

0239 Created, and 2 approaches added using python

---

solutions/1600-1699/1657-define-if-two-strings-are-close-medium.md

Create md file for solution 1657 - Determine if Two Strings Are Close (Medium).

Create solution for 1657-Determine if Two Strings Are Close (Medium)

---

solutions/0000-0099/0070-climbing-stairs-easy.md

The purpose of this PR is to add coding solution and approach in Python for the LeetCode [Climbing Stairs](https://leetcode.com/problems/climbing-stairs/) problem.

Added Python solution and approach for 0070 - Climbing Stairs.

---

solutions/0000-0099/0074-search-a-2d-matrix-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/) problem.

Added Python solution for 0074 - Search a 2D Matrix.

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

The purpose of this PR is to add two coding solutions in Python for the LeetCode [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/) problem.

Added two Python solutions for 0088 - Merge Sorted Array.

---

solutions/0100-0199/0150-evaluate-reverse-olish-notation-medium.md

Created md file for leetcode 0150, added approach using stack, and solution using python.

Created 0150, approach 1, using python

---

solutions/0000-0099/0022-generate-parentheses-medium.md

Created md for lc 0022. Added approach 1 using backtracking, and solution using python.
Could probably have someone with a better understanding of math breakdown the Time complexity further.

0022 created, and python solution added.

---

solutions/0700-0799/0739-daily-temperatures-medium.md

Created 0739-daily-temperatures-medium.md
Added Approach 1: Monotonic Stack
Added Solution using Python.

0739 created, using Python.

---

solutions/0100-0199/0101-symmetric-tree-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Symmetric Tree](https://leetcode.com/problems/symmetric-tree/) problem.

Added Python solution for 0101 - Symmetric Tree.

---

solutions/0800-0899/0853-car-fleet-medium.md

Created 0853-car-fleet-medium.md
Added Approach 1 Monotonic Stack and Approach 2: Reverse Sorting
Added solutions using python.

0853 created, with 2 approaches using python.

---

solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal/) problem.

Added Python solution for 0102 - Binary Tree Level Order Traversal.

---

solutions/0100-0199/0104-maximum-depth-of-binary-tree-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree/) problem.

Added Python solution for 0104 - Maximum Depth Of Binary Tree.

---

solutions/0100-0199/0141-linked-list-cycle.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Linked List Cycle](https://leetcode.com/problems/linked-list-cycle/) problem.

Added JavaScript solution for 0141 - Linked List Cycle.

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/) problem.

Added Python solution for 0144 - Binary Tree Preorder Traversal.

---

solutions/0700-0799/0704-binary-search-easy.md

Added Approach 1: Linear Scan to gather insight on how binary search may work, with Python solution
Changed Approach 1 Binary Search --> Approach 2:
Added Python versions of code to Approach 2.

0704 Updated Binary Search with potential intuition.

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/) problem.

Added JavaScript solution for 0144 - Binary Tree Preorder Traversal.

---

solutions/0800-0899/0875-koko-eating-bananas-medium.md

Create 0875 Koko Eating Bananas
Added Approach 1: Brute Force and Approach 2: Binary Search
Added Solutions using Python

0875 2 approaches, 2 solutions using python

---

solutions/1100-1199/1143-longest-common-subsequence-medium.md

This PR contains a Java solution to Leetcode [Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/) problem.

Added Java solution for 1143 - Longest Common Subsequence, and also applied cleanup on Approach section

---

solutions/0100-0199/0104-maximum-depth-of-binary-tree-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree/) problem.

Added JavaScript solution for 0104 - Maximum Depth of Binary Tree.

---

solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal/) problem.

Added JavaScript solution for 0102 - Binary Tree Level Order Traversal.

---

solutions/0100-0199/0101-symmetric-tree-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Symmetric Tree](https://leetcode.com/problems/symmetric-tree/) problem.

Added JavaScript solution for 0101 - Symmetric Tree.

---

solutions/0100-0199/0148-sort-list-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Sort List](https://leetcode.com/problems/sort-list/) problem.

Added JavaScript solution for 0148 - Sort List.

---

solutions/0100-0199/0169-majority-element-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Majority Element](https://leetcode.com/problems/majority-element/) problem.

Added Python and JS solution for 0169 - Majority Element.

---

solutions/0900-0999/0981-time-based-key-value-store-medium.md

0981 Time Based Key-Value Store
- Added python solution to binary search approach
- Fixed formatting of question.

0981, python solution, fixed question formatting.

---

solutions/0100-0199/0191-number-of-1-bits-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Number of 1 Bits](https://leetcode.com/problems/number-of-1-bits/) problem.

Added Python and JavaScript solution for 0191 - Number of 1 Bits.

---

solutions/0000-0099/0004-median-of-two-sorted-arrays-hard.md

Created 0004-median-of-two-sorted-arrays-hard.md
Added Approach 1: Linear Search, Approach 2: Binary Search
Added Solutions using Python.

0004 create, 2 solutions using Python added

---

solutions/0200-0299/0206-reverse-linked-list-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Reverse Linked List](https://leetcode.com/problems/reverse-linked-list/) problem.

Added JavaScript solution for 0206 - Reverse Linked List.

---

solutions/0100-0199/0143-reorder-list-medium.md

Created 0143-reorder-list-medium.md
Added Approach 1:  Iterative using 2 pointers.
Added Solution using Python.

0143 Created, 1 Approach using Python added.

---

solutions/0200-0299/0217-contains-duplicate-easy.md

The purpose of this PR is to add coding solutions in JavaScript and Python for the LeetCode [Contains Duplicate](https://leetcode.com/problems/contains-duplicate/) problem.

Added Python and JavaScript solutions for 0217 - Contains Duplicate.

---

solutions/0200-0299/0234-palindrome-linked-list-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/) problem.

Added JavaScript solution for 0234 - Palindrome Linked List.

---

solutions/0200-0299/0234-palindrome-linked-list-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/) problem.

Added JavaScript and Python solution for 0234 - Palindrome Linked List.

---

solutions/0200-0299/0242-valid-anagram-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [Valid Anagram](https://leetcode.com/problems/valid-anagram/) problem.

Added Python and JavaScript solution for 0242 - Valid Anagrams.

---

solutions/0200-0299/0268-missing-number-easy.md

The purpose of this PR is to add coding solutions in Python and JavaScript for the LeetCode [Missing Number](https://leetcode.com/problems/missing-number/) problem.

Added Python and JavaScript solution for 0268 - Missing Number.

---

solutions/0200-0299/0278-first-bad-version-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [First Bad Version](https://leetcode.com/problems/first-bad-version/) problem.

Added Python and JavaScript solution for 0278 - First Bad Version.

---

solutions/0200-0299/0283-move-zeroes-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [Move Zeroes](https://leetcode.com/problems/move-zeroes/) problem.

Added Python and JavaScript solution for 0283 - Move Zeroes.

---

solutions/0200-0299/0287-find-the-duplicate-number-medium.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/) problem.

Added Python and JavaScript solution for 0287 - Find the Duplicate Number.

---

solutions/0300-0399/0344-reverse-string-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [Reverse String.](https://leetcode.com/problems/reverse-string/) problem.

Added Python and JavaScript solutions for 0344 - Reverse String.

---

solutions/0500-0599/0589-n-ary-tree-preorder-traversal-easy.md

The purpose of this PR is to add coding solution in Python and JavaScript for the LeetCode [N-ary Tree Preorder Traversal](https://leetcode.com/problems/n-ary-tree-preorder-traversal/) problem.

Added Python and JavaScript solution for 0589 - N-ary Tree Preorder Traversal.

---

solutions/0700-0799/0704-binary-search-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Search](https://leetcode.com/problems/binary-search/) problem.

Added JavaScript solution for 0704 - Binary Search.

---

solutions/0700-0799/0733-flood-fill-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Flood Fill](https://leetcode.com/problems/flood-fill/) problem.

Added JavaScript solution for 0733 - Flood Fill.

---

solutions/0800-0899/0841-keys-and-rooms-medium.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Keys and Rooms](https://leetcode.com/problems/keys-and-rooms/) problem.

Added Python and JavaScript solution for 0841 - Keys and Rooms.

---

solutions/1800-1899/1833-maximum-ice-cream-bars-medium.md

This is a PR to add a solution for [Problem#1833. Maximum Ice Cream Bars](https://leetcode.com/problems/maximum-ice-cream-bars/)

Added 1833-maximum-ice-cream-bars-medium.md

---

solutions/0800-0899/0844-backspace-string-compare-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Backspace String Compare](https://leetcode.com/problems/backspace-string-compare/) problem.

Added Python and JavaScript solution for 0844 - Backspace String Compare.

---

solutions/0800-0899/0881-boats-to-save-people-medium.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Boats to Save People](https://leetcode.com/problems/boats-to-save-people/) problem.

Added Python and JavaScript solution for 0881 - Boats to Save People.

---

solutions/0900-0999/0901-online-stock-span-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Online Stock Span](https://leetcode.com/problems/online-stock-span/) problem.

Added JavaScript solution for 0901 - Online Stock Span.

---

src/css/custom.css

Description
Successfully changed the foot-link-hover-colour-changed. 
Current Design
Better Design 

[UI] Footer elements Visibility

---

solutions/0100-0199/0138-copy-list-with-random-pointer-medium.md

Created 0138-copy-list-with-random-pointer-medium.md
Added Approach 1: 2 Passes and Approach 2:  Single Pass
Added solutions using Python.

0138 created, 2 approaches added with solutions in Python

---

src/css/custom.css

Issue #394 fixes
wrapping navbar-icon css inside @media screen and (min-width: 997px) {} to fix icons not aligning, and behaving differently on smaller viewpoints. 
Old View:
New View:

CSS fixes for Icons inside hamburger menus

---

solutions/0900-0999/0941-valid-mountain-array-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Valid Mountain Array](https://leetcode.com/problems/valid-mountain-array/) problem.

Added Python and JavaScript solution for 0941 - Valid Mountain Array.

---

solutions/1000-1099/1047-remove-all-adjacent-duplicates-in-string-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Remove All Adjacent Duplicates in String](https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/) problem.

Added JavaScript solution for 1047 - Remove All Adjacent Duplicates in String.

---

solutions/0000-0099/0002-add-two-numbers-medium.md

Created 0002-add-two-numbers-medium.md
Added Approach 1: Iterative
Added solutions using Python.

0002 create, approach 1 and 1 python solution added

---

solutions/1100-1199/1143-longest-common-subsequence-medium.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/) problem.

Added Python and JavaScript solution for 1143 - Longest Common Subsequence.

---

solutions/1400-1499/1443-minimum-time-to-collect-all-apples-in-a-tree.md

This is a PR for adding a solution for problem #1443

Added #1443 - Minimum Time to Collect All Apples in a Tree (Medium)

---

solutions/1400-1499/1480-running-sum-of-1d-array-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Running Sum of 1d Array](https://leetcode.com/problems/running-sum-of-1d-array/) problem

Added JavaScript solution for 1480 - Running Sum of 1d Array.

---

solutions/1400-1499/1480-running-sum-of-1d-array-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Running Sum of 1d Array](https://leetcode.com/problems/running-sum-of-1d-array/) problem

Added Python solution for 1480 - Running Sum of 1d Array.

---

solutions/1600-1699/1672-richest-customer-wealth-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Customer Wealth](https://leetcode.com/problems/richest-customer-wealth/) problem.

Added Python and JavaScript solution for 1672 - Customer Wealth.

---

solutions/0100-0199/0146-lru-cache-medium.md

Created 0146-lry-cache-medium.md
Added Approach 1: Doubly-Linked List
Added Solution using Python

lru-cache-medium approach 1, and python solution

---

solutions/2200-2299/2279-maximum-bags-with-full-capacity-of-rock-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Maximum Bags With Full Capacity of Rocks](https://leetcode.com/problems/maximum-bags-with-full-capacity-of-rocks/) problem

Added Python solution for 2279 - Maximum Bags With Full Capacity of Rock.

---

solutions/2200-2299/2279-maximum-bags-with-full-capacity-of-rock-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Maximum Bags With Full Capacity of Rocks](https://leetcode.com/problems/maximum-bags-with-full-capacity-of-rocks/) problem.

Added JavaScript solution for 2279 - Maximum Bags With Full Capacity of Rocks.

---

solutions/0000-0099/0001-two-sum.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Two Sum](https://leetcode.com/problems/two-sum/) problem.

Added JavaScript solution for 0001 - Two Sum.

---

solutions/0000-0099/0002-add-two-numbers-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/) problem.

Added JavaScript solution for 0002 - Add Two Numbers.

---

solutions/0000-0099/0007-reverse-integer-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/) problem.

Added Python solution for 0007 - Reverse Integer.

---

solutions/0000-0099/0009-palindrome-number-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Palindrome Number](https://leetcode.com/problems/palindrome-number/) problem.

Added JavaScript solution for 0009 - Palindrome Number.

---

solutions/0200-0299/0226-invert-binary-tree-easy.md

Created 0226-invert-binary-tree-easy.md
Added Approach 1: Recursive Depth-First Search, Approach 2: Iterative Depth-First Search and Approach 3: Iterative Breadth-First Search.
Added solution using Python for all of them.

0226 created, 3 approaches and 3 solutions using python.

---

solutions/0000-0099/0013-roman-to-integer-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Roman to Integer](https://leetcode.com/problems/roman-to-integer/) problem.

Added JavaScript solution for 0013 - Roman to Integer.

---

solutions/0100-0199/0104-maximum-depth-of-binary-tree-easy.md

Added Approach 2: Iterative Depth-First Search and Approach 3: Iterative Breadth-First Search
Added 2 solutions using Python.

0104 2 approaches added using python solutions

---

solutions/0000-0099/0014-longest-common-prefix-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/) problem.

Added JavaScript solution for 0014 - Longest Common Prefix.

---

solutions/0500-0599/0543-diameter-of-binary-tree-easy.md

0543-diameter-of-binary-tree-easy.md created
Added Approach 1: Recursive Depth-First Search
Added solution using Python.

0543 created, 1 approach added, and 1 python solution.

---

solutions/0000-0099/0014-longest-common-prefix-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/) problem.

Added Python solution for 0014 - Longest Common Prefix.

---

solutions/0000-0099/0017-letter-combinations-of-a-phone-number-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Letter Combinations Of A Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number/) problem.

Added Python solution for 0017 - Letter Combinations Of A Phone Number.

---

solutions/0000-0099/0017-letter-combinations-of-a-phone-number-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Letter Combinations Of A Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number/) problem.

Added JavaScript solution for 0017 - Letter Combination of a Phone Number.

---

solutions/0100-0199/0100-same-tree-easy.md

0100-same-tree-easy.md created
2 Approaches, 1: Recursive Depth-First Search and 2:Iterative Depth-First Search added.
2 solutions using Python.

0100 created, 2 approaches with 2 solution using Python

---

solutions/0000-0099/0019-remove-nth-node-from-end-of-list-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/) problem.

Added JavaScript solution for 0019 - Remove Nth Node From End of List.

---

solutions/0500-0599/0572-subtree-of-another-tree-easy.md

0572 python solution added.

---

solutions/0200-0299/0235-lowest-common-ancestor-of-a-binary-search-tree-medium.md

0235-lowest-common-ancestor-of-a-binary-search-tree-medium.md created.
1 Approach, Approach 1: Iterative created
1 solution using Python.

0235 created with 1 approach and 1 solution using Python

---

solutions/0000-0099/0021-merge-two-sorted-lists-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/) problem.

Added JavaScript solution for 0021 - Merge Two Sorted Lists.

---

solutions/0100-0199/0199-binary-tree-right-side-view-medium.md

Added a approach to 0199: Approach 2: Breadth-First Search
Added solution using Python. 

0199 1 approach added, 1 solution using Python

---

solutions/0000-0099/0023-merge-k-sorted-lists-hard.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Merge K Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists/) problem.

Added JavaScript solution for 0023 - Merge K Sorted Lists.

---

solutions/0200-0299/0230-kth-smallest-element-in-a-bst-medium.md

0230-kth-smallest-element-in-a-bst-medium.md
2 approaches, Recursive Inorder Traversal and Iterative Inorder Traversal.
2 python solutions added.

0230 created, 2 approaches with 2 python solutions added.

---

solutions/0000-0099/0024-swap-nodes-in-pairs-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs/) problem.

Added JavaScript solution for 0024 - Swap Nodes in Pairs.

---

solutions/0100-0199/0105-construct-binary-tree-from-preorder-and-inorder-traversal-medium.md

0105-construct-binary-tree-from-preorder-and-inorder-traversal-medium.md created
1 Approach, Approach 1: Recursion and Array Slicing created.
1 solution added using python.

0105 created, 1 approach, 1 python solution

---

solutions/0200-0299/0208-implement-trie-medium.md

Added Python solution to 0208.

added python solution to 0208

---

solutions/0000-0099/0026-Remove-Duplicates-from-Sorted-Array-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Remove Duplicates from Sorted Array](https://leetcode.com/problems/remove-duplicates-from-sorted-array/) problem.

Added Python and JavaScript solution for 0026 - Remove Duplicates from Sorted Array.

---

solutions/0000-0099/0033-search-in-rotated-sorted-array-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/) problem.

Added JavaScript solution for 0033 - Search in Rotated Sorted Array.

---

tutorials/graph-theory/bellman-ford-algorithm.md

Included python implementation of bellman ford algorithm

Included python implementation of bellman ford algorithm

---

solutions/0000-0099/0034-find-first-and-last-position-of-element-in-sorted-array-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/) problem.

Added JS solution for 0034 - Find First and Last Position of Element in Sorted Array.

---

solutions/0200-0299/0211-design-add-and-search-words-data-structure-medium.md

0211-design-add-and-search-words-data-structure-medium.md created
1 approach: Approach 1: Trie - Depth-First Search
1 solution using Python

0211 created, 1 approach, 1 python solution

---

solutions/0000-0099/0034-find-first-and-last-position-of-element-in-sorted-array-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/) problem.

Added Python solution for 0034 - Find First and Last Position of Element in Sorted Array.

---

solutions/0200-0299/0212-word-search-ii-hard.md

0212-word-search-ii-head.md created
Approach 1:  Iterative DFS using a Trie added
1 solution using python.

0212 created, 1 solution, 1 approach

---

solutions/0000-0099/0035-search-insert-position-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Search Insert Position](https://leetcode.com/problems/search-insert-position/) problem.

Added JavaScript solution for 0035 - Search Insert Position.

---

solutions/0700-0799/0703-kth-largest-element-in-a-stream-easy.md

Added python solution to approach 1, tags.

0703 python solution added, tags

---

solutions/0000-0099/0042-trapping-rain-water-hard.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water/) problem.

Added JavaScript solution for 0042 - Trapping Rain Water.

---

solutions/1000-1099/1046-last-stone-weight-easy.md

1046-last-stone-weight-easy.md created
1 approach, Approach 1: Heap/Priority Queue
1 solution using Python

1046 created, 1 approach, 1 solution using Python

---

solutions/0900-0999/0973-k-closest-points-to-origin-medium.md

1 Approach: Approach 1: Quick Select
Solution using python.
Time/Space for heap approach
Added tabs/tab items for existing
tags

0973 new approach, python solution, tags, time complexity, tabs

---

solutions/0000-0099/0048-rotate-image-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Rotate Image](https://leetcode.com/problems/rotate-image/) problem.

Added JavaScript solution for 0048 - Rotate Image.

---

solutions/0000-0099/0057-insert-interval-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Insert Interval](https://leetcode.com/problems/insert-interval/ ) problem.

Added JavaScript solution for 0057 - Insert Interval.

---

solutions/0000-0099/0048-rotate-image-medium.md
solutions/0600-0699/0653-two-sum-IV-input-is-a-BST-easy.md

The purpose of this PR is to add the solution in C++ for the LeetCode [Two Sum IV - Input is a BST](https://leetcode.com/problems/two-sum-iv-input-is-a-bst/) problem.

0653 created,1 approach, 1 C++ solution

---

solutions/0000-0099/0062-unique-paths-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Unique Paths](https://leetcode.com/problems/unique-paths/) problem.

Added JavaScript solution for 0062 - Unique Paths.

---

solutions/0200-0299/0215-kth-largest-element-in-an-array-medium.md

0215 Added 1 approach: Approach 3: Quick Select
- Time complexity to priority queue
- added tabs, quick select tag.
- 2 python solutions

0215 added 2 python solutions, 1 new approach.

---

solutions/0000-0099/0069-sqrt-x-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Sqrt(x)](https://leetcode.com/problems/unique-paths/) problem.

Added Python solution for 0069 - Sqrt(x).

---

solutions/0600-0699/0621-task-scheduler-medium.md

0621-task-scheduler-medium.md created
2 approaches: Approach 1: Heap and Queue, Approach 2: Greedy
2 python solutions

0621 created, 2 approaches, 2 python solutions

---

solutions/0300-0399/0355-design-twitter-medium.md

0355-design-twitter-medium.md
1 approach created - Approach 1: Heap/Priority Queue
1 python solution

0355, 1 approach, 1 python solution

---

solutions/0000-0099/0069-sqrt-x-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Sqrt(x)](https://leetcode.com/problems/unique-paths/) problem.

Added JavaScript solution for 0069 - Sqrt(x).

---

solutions/0200-0299/0295-find-median-from-data-stream-hard.md

0295-find-median-from-data-stream-hard.md
1 approach: Approach 1: 2 Heaps/Priority Queues
1 python solution
**If you haven't fulfilled the below requirements or even delete the entire ### General

0295 created, 1 approach, 1 python solution

---

solutions/0000-0099/0070-climbing-stairs-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Climbing Stairs](https://leetcode.com/problems/climbing-stairs/) problem.

Added JavaScript solution for 0070 - Climbing Stairs.

---

solutions/0000-0099/0078-subsets-medium.md

Added in the tags, added iterative python solution for backtracking

0078 python solution

---

solutions/0000-0099/0075-sort-colors-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Sort Colors](https://leetcode.com/problems/sort-colors/) problem.

Added JavaScript solution for 0075 - Sort Colors.

---

solutions/0000-0099/0075-sort-colors-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Sort Colors](https://leetcode.com/problems/sort-colors/) problem.

Added Python solution for 0075 - Sort Colors.

---

solutions/0000-0099/0039-combination-sum-medium.md

Added:
- Approach 1: Dynamic Programming - Tabulation
- tags

0039 dp approach, 1 python solution

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/) problem.

Added JavaScript solution for 0088 - Merge Sorted Array.

---

solutions/0000-0099/0040-combination-sum-ii-medium.md

0040 python solution

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/) problem.

Added Python solution for 0088 - Merge Sorted Array.

---

solutions/0000-0099/0079-word-search-medium.md

- 0079-word-search-medium.md created
- 1 approach: Approach 1: Backtracking created
- 1 python solution added

0079, 1 approach, 1 solution

---

solutions/0000-0099/0094-binary-tree-inorder-traversal-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) problem.

Added JavaScript solution for 0094 - Binary Tree Inorder Traversal.

---

solutions/0100-0199/0131-palindrome-partitioning-medium.md

Added content to 0131 - Palindrome Partitioning
- Approach 2:  Iterative Backtracking
- python solution

0131 1 approach, 1 python solution

---

solutions/0000-0099/0094-binary-tree-inorder-traversal-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) problem.

Added C++ solution for 0094 - Binary Tree Inorder Traversal.

---

solutions/0000-0099/0098-validate-binary-search-tree-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Validate Binary Search Tree](https://leetcode.com/problems/validate-binary-search-tree/) problem.

Added C++ solution for 0098 - Validate Binary Search Tree.

---

solutions/0000-0099/0051-n-queens-hard.md

- 0051-n-queens-hard.md created
- 1 approach - Approach 1: Backtracking

0051 created, 1 approach, 1 python solution

---

solutions/0000-0099/0098-validate-binary-search-tree-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Validate Binary Search Tree](https://leetcode.com/problems/validate-binary-search-tree/) problem.

Added JavaScript solution for 0098 - Validate Binary Search Tree.

---

solutions/0000-0099/0002-add-two-numbers-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/) problem.

Added C++ solution for 0002 - Add Two Numbers.

---

solutions/0100-0199/0133-clone-graph-medium.md

- 0133 draft complete
- Approach 1:  Iterative Depth/Breadth-First Search
- python solution

0133 1 approach, 1 solution

---

solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Longest Substring Without Repeating Character](https://leetcode.com/problems/longest-substring-without-repeating-characters/) problem.

Added C++ solution for 0003 - Longest Substring Without Repeating Character.

---

solutions/0600-0699/0695-max-area-of-island-medium.md

- 0695-max-area-of-island-medium.md created
- 1 approach, Approach 1: Breadth-First Search

0695, 1 approach, 1 solution

---

solutions/0000-0099/0003-longest-substring-without-repeating-characters-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/) problem.

Added C++ solution for 0003 - Longest Substring Without Repeating Characters.

---

solutions/0000-0099/0007-reverse-integer-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Reverse Integer](https://leetcode.com/problems/reverse-integer/) problem.

Added C++ solution for 0007 - Reverse Integer.

---

solutions/0000-0099/0009-palindrome-number-easy.md

The purpose of this PR is to add coding solutions in C++ for the LeetCode [Palindrome Number](https://leetcode.com/problems/palindrome-number/) problem.

Added C++ solutions for 0009 - Palindrome Number.

---

solutions/0400-0499/0417-pacific-atlantic-water-flow-medium.md

0417
- 1 approach: Approach 2: Breadth-First Search

0417, 1 approach, 1 python solution

---

solutions/0000-0099/0012-integer-to-roman-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Integer to Roman](https://leetcode.com/problems/integer-to-roman/) problem.

Added C++ solution for 0012 - Integer to Roman.

---

solutions/0100-0199/0130-surrounded-regions-medium.md

- 0130-surrounded-regions-medium.md created
- 1 approach, Approach 1: Breath-First Search

0130, 1 approach, 1 solution

---

solutions/0000-0099/0013-roman-to-integer-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Roman to Integer](https://leetcode.com/problems/roman-to-integer/) problem.

Added C++ solution for 0013 - Roman to Integer.

---

solutions/0900-0999/0994-rotting-oranges-medium.md

- 0994-rotting-oranges-medium.md created
- 1 approach, Approach 1: Breadth-First Search created
- 1 python solution added. 

0994 created

---

solutions/0000-0099/0014-longest-common-prefix-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/) problem.

Added C++ solution for 0014 - Longest Common Prefix.

---

solutions/0200-0299/0207-course-schedule-medium.md

0207 python solution

---

solutions/0000-0099/0017-letter-combinations-of-a-phone-number-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Letter Combination of a Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number/) problem.

Added C++ solution for 0017 - Letter Combination of a Phone Number.

---

solutions/0200-0299/0210-course-schedule-ii-medium.md

- added python solution to 0210

0210 1 python solution

---

solutions/0000-0099/0019-remove-nth-node-from-end-of-list-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/) problem.

Added Python solution for 0019 - Remove Nth Node From End of List.

---

solutions/0000-0099/0019-remove-nth-node-from-end-of-list-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/) problem.

Added C++ solution for 0019 - Remove Nth Node From End of List.

---

solutions/0600-0699/0684-redundant-connection-medium.md

- 0684-leetcode-the-hard-way
- added 1 approach: Approach 1: Union Find
- added python solution

0684, 1 approach, 1 solution

---

solutions/0000-0099/0021-merge-two-sorted-lists-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/) problem.

Added C++ solution for 0021 - Merge Two Sorted Lists.

---

solutions/0100-0199/0127-word-ladder-hard.md

- 0127, added python solution
- added tags, time/space complexity, and a graph.

0127 python solution

---

solutions/0000-0099/0024-swap-nodes-in-pairs-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs) problem.

Added C++ solution for 0024 - Swap Nodes in Pairs.

---

solutions/0000-0099/0026-Remove-Duplicates-from-Sorted-Array-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Remove Duplicates From Sorted Array](https://leetcode.com/problems/remove-duplicates-from-sorted-array/) problem.

Added C++ solution for 0026 - Remove Duplicates From Sorted Array.

---

solutions/0000-0099/0028-find-the-index-of-the-first-occurrence-in-a-string-easy.md

- The purpose of this PR is to add coding solution in C++, JavaScript and Python for the LeetCode [Find the Index of the First Occurrence in a String](hhttps://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/) problem.
- Updated the name of the file from "0028 - Implement strStr() (Easy)" to "0028 - Find the Index of the First Occurrence in a String (Easy)", because the name of the problem changed a few months ago.

Added C++, JS and Py solution for 0028 - Find the Index of the First Occurrence in a String.

---

solutions/1500-1599/1584-min-cost-to-connect-all-points-medium.md

Contributed to 1584
- 1 approach: Prim's Algorithm
- 1 solution
- tags, tabs

1584, 1 approach, 1 solution

---

solutions/0000-0099/0033-search-in-rotated-sorted-array-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/) problem.

Added C++ solution for 0033 - Search in Rotated Sorted Array.

---

solutions/0000-0099/0039-combination-sum-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Combination Sum](https://leetcode.com/problems/combination-sum/) problem.

Added JS solution for 0039 - Combination Sum.

---

solutions/0000-0099/0040-combination-sum-ii-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Combination Sum II](https://leetcode.com/problems/combination-sum-ii/) problem.

Added JS solution for 0040 - Combination Sum II.

---

solutions/0000-0099/0042-trapping-rain-water-hard.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water/) problem.

Added C++ solution for 0042 - Trapping Rain Water.

---

solutions/0700-0799/0743-network-delay-time-medium.md

- tags, tabs, python solution.

0743 python solution

---

solutions/0000-0099/0045-jump-game-ii-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Jump Game II](https://leetcode.com/problems/jump-game-ii/) problem.

Added JS solution for 0045 - Jump Game II.

---

solutions/0000-0099/0049-group-anagrams-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Group Anagrams](https://leetcode.com/problems/group-anagrams/) problem.

Added JS solution for 0049 - Group Anagrams.

---

solutions/0700-0799/0787-cheapest-flights-within-k-stops-medium.md

- tags, edited misnumbered approach number.
- 1 approach, Approach 3: Dijkstra's Algorithm

0787, 1 approach, 1 solution

---

solutions/0700-0799/0746-min-cost-climbing-stairs-easy.md

- 0746-min-cost-climbing-stairs-easy.md created
- 1 approach, Approach 1: Dynamic Programming created

0746 created, 1 approach, 1 solution

---

solutions/0000-0099/0061-rotate-list-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Rotate List](https://leetcode.com/problems/rotate-list/) problem.

Added Python solution for 0061 - Rotate List.

---

solutions/0000-0099/0061-rotate-list-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Rotate List](https://leetcode.com/problems/rotate-list/) problem.

Added JS solution for 0061 - Rotate List.

---

solutions/0000-0099/0074-search-a-2d-matrix-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/) problem.

Added C++ solution for 0074 - Search a 2D Matrix.

---

solutions/0000-0099/0074-search-a-2d-matrix-medium.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/) problem.

Added Python solution for 0074 - Search in a 2D Matrix.

---

solutions/0200-0299/0213-house-robber-ii-medium.md

- 0213-house-robber-ii-medium.md created
- 1 approach, Approach 1: Dynamic Programming created
- 1 python solution added.

0213 created, 1 approach, 1 solution

---

solutions/0000-0099/0088-merge-sorted-array-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/) problem.

Added C++ solution for 0088 - Merge Sorted Array.

---

solutions/1400-1499/1448-count-good-nodes-in-binary-tree-medium.md

- Added python solution
-  added tabs

1448 python solution

---

solutions/0100-0199/0100-same-tree-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Same Tree](https://leetcode.com/problems/same-tree/) problem.

Added C++ solution for 0100 - Same Tree.

---

solutions/0100-0199/0104-maximum-depth-of-binary-tree-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree/) problem.

Added C++ solution for 0104 - Maximum Depth of Binary Tree.

---

solutions/0100-0199/0113-path-sum-ii-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Path Sum II](https://leetcode.com/problems/path-sum-ii/) problem.

Added JS solution for 0113 - Path Sum II.

---

solutions/0100-0199/0139-word-break-medium.md

- 0139-word-break-medium.md created
- 1 approach, Approach 1: Dynamic Programming created

0139 created, 1 approach, 1 solution

---

solutions/0100-0199/0121-best-time-to-buy-and-sell-stock-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/) problem.

Added JS solution for 0121 - Best Time to Buy and Sell Stock.

---

solutions/0100-0199/0121-best-time-to-buy-and-sell-stock-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/) problem.

Added C++ solution for 0121 - Best Time to Buy and Sell Stock.

---

solutions/0100-0199/0136-single-number-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Single Number](https://leetcode.com/problems/single-number/) problem.

Added JS solution for 0136 - Single Number.

---

solutions/0100-0199/0136-single-number-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Single Number](https://leetcode.com/problems/single-number/) problem.

Added Python solution for 0136 - Single Number.

---

solutions/0300-0399/0300-longest-increasing-subsequence-medium.md

- created 0300-longest-increasing-subsequence-medium.md
- 2 approaches: Approach 1: Dynamic Programming, Approach 2: Binary Search
- 2 solutions, 1 for each approach.

0300 created, 2 approaches, 2 solutions

---

solutions/0400-0499/0416-partition-equal-subset-sum-medium.md

- 0416-partition-equal-subset-sum-medium.md created
- 1 approach, Approach 1: Dynamic Programming
- 1 solution using python.

0416 created, 1 approach, 1 solution

---

solutions/0100-0199/0143-reorder-list-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Reorder List](https://leetcode.com/problems/reorder-list/) problem.

Added JS solution for 0143 - Reorder List.

---

solutions/0000-0099/0062-unique-paths-medium.md

- added missing tags
- added python solution for approach 2.

tags, and solution for approach 2.

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/) problem.

Added C++ solution for 0144 - Binary Tree Preorder Traversal.

---

solutions/0100-0199/0144-binary-tree-preorder-traversal-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/) problem.

Added JS solution for 0144 - Binary Tree Preorder Traversal.

---

solutions/0300-0399/0309-best-time-to-buy-and-sell-stock-with-cooldown-medium.md

- 0309-best-time-to-buy-and-sell-stock-with-cooldown-medium.md created
- 1 approach, Approach 1: Dynamic Programming added.
- 1 solution using python

0309 created, 1 approach, 1 solution

---

solutions/0500-0599/0518-coin-change-2-medium.md

0518
- added time and space for approach 1
- added python solution for approach 1.

0518 python solution, time/space complexity

---

solutions/0400-0499/0494-target-sum-medium.md

- 0494-target-sum-medium.md
- 1 approach, Approach 1: Dynamic Programming - Memoization
- 1 solution using python

0494 created, 1 approach 1 solution

---

solutions/0100-0199/0198-house-robber-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [House Robber](https://leetcode.com/problems/house-robber/) problem.

Added JS solution for 0199 - House Robber.

---

solutions/0000-0099/0097-interleaving-string-medium.md

- 0097-interleaving-string-medium.md created
- 1 approach: Approach 1: 2D Dynamic Programming created
- 1 solution

0097 created, 1 approach, 1 solution

---

solutions/0100-0199/0199-binary-tree-right-side-view-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view/) problem.

Added C++ solution for 0199 - Binary Tree Right Side View.

---

solutions/0100-0199/0199-binary-tree-right-side-view-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view/) problem.

Added JS solution for 0199 - Binary Tree Right Side View.

---

solutions/0200-0299/0205-isomorphic-strings-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Isomorphic Strings](https://leetcode.com/problems/isomorphic-strings/) problem.

Added Python solution for 0205 - Isomorphic Strings.

---

solutions/0300-0399/0329-longest-increasing-path-in-a-matrix-hard.md

- 0329-longest-increasing-path-in-a-matrix-hard.md created
- 2 approaches, Approach 1: Dynamic Programming - Memoization, Approach 2: Topological Sort.
- 1 python solution for each.

0329 created, 2 approach, 1 solution each.

---

solutions/0200-0299/0206-reverse-linked-list-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Reverse Linked List](https://leetcode.com/problems/reverse-linked-list/) problem.

Added C++ solution for 0206 - Reverse Linked List.

---

solutions/0100-0199/0115-distinct-subsequences-hard.md

0115 content
- added tags, and tabs
- 1 solution to previous approach
- Approach 3:  Dynamic Programming - Memoization

0115, 2 solutions, 1 approach

---

solutions/0000-0099/0072-edit-distance-hard.md

0072
- 1 approach, Approach 2: Dynamic Programming - Memoization

0072 1 approach 1 solution

---

solutions/0300-0399/0312-burst-balloons-hard.md

- 0312-burst-balloons-hard.md created
- 1 approach, Approach 1: Dynamic Programming - Memoization
- 1 python solution 

0312 1 approach 1 solution

---

solutions/0200-0299/0217-contains-duplicate-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Contains Duplicate](https://leetcode.com/problems/contains-duplicate/) problem.

Added C++ solution for 0217 - Contains Duplicates.

---

solutions/0000-0099/0010-regular-expression-matching-hard.md

- 0010-regular-expression-matching-hard.md created
- 1 approach, Approach 1: Dynamic Programming- Memoization
- 1 python solution 

0010 create, 1 solution, 1 approach

---

solutions/0000-0099/0053-maximum-subarray-medium.md

- 0053-maximum-subarray-medium.md created
- 1 approach, Approach 1: Kadane's Algorithm created

0053, 1 solution 1 approach

---

solutions/0200-0299/0226-invert-binary-tree-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/) problem.

Added JS solution for 0226 - Invert Binary Tree.

---

solutions/0000-0099/0055-jump-game-medium.md

- 0055-jump-game-medium.md created
- 1 approach, Approach 1: Greedy created

0055 created, 1 approach, 1 solution

---

solutions/0200-0299/0226-invert-binary-tree-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/) problem.

Added C++ solution for 0226 - Invert Binary Tree.

---

solutions/0200-0299/0230-kth-smallest-element-in-a-bst-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst/) problem.

Added JS solution for 0230 - Kth Smallest Element in a BST.

---

solutions/1800-1899/1899-merge-triplets-to-form-target-triplet-medium.md

- 1899-merge-triplets-to-form-target-triplet-medium.md created
- 1 approach, Approach 1: Greedy created

1899 created, 1 approach, 1 solution

---

solutions/0200-0299/0230-kth-smallest-element-in-a-bst-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst/) problem.

Added C++ solution for 0230 - Kth Smallest Element in a BST.

---

solutions/0600-0699/0678-valid-parenthesis-string-medium.md

- 0678-valid-parenthesis-string-medium.md created
- 1 approach, Approach 1: Greedy created

0678 created, 1 approach, 1 solution

---

solutions/0200-0299/0231-power-of-two-easy.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Power of Two](https://leetcode.com/problems/power-of-two/) problem.

Added JS and Python solution for 0231 - Power of Two.

---

solutions/0200-0299/0235-lowest-common-ancestor-of-a-binary-search-tree-medium.md

The purpose of this PR is to add coding solution in JavaScript and Python for the LeetCode [Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/) problem.

Added JS solution for 0235 - Lowest Common Ancestor of a Binary Search Tree.

---

solutions/0200-0299/0235-lowest-common-ancestor-of-a-binary-search-tree-medium.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/) problem.

Added C++ solution for 0235 - Lowest Common Ancestro of a Binary Search Tree.

---

solutions/0000-0099/0056-merge-intervals-medium.md

- 0056-merge-intervals-medium.md created
- 1 approach, Approach 1: Sorting created

0056 created, 1 approach, 1 solution

---

solutions/0200-0299/0268-missing-number-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Missing Number](https://leetcode.com/problems/missing-number/) problem.

Added JS solution for 0268 - Missing Number.

---

solutions/0400-0499/0435-non-overlapping-intervals-medium.md

0435 - Non-overlapping Intervals
- added tags, tabs, time/space and python solution

0435 python solution, tags, time/space

---

solutions/0200-0299/0268-missing-number-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Missing Number](https://leetcode.com/problems/missing-number/) problem.

Added Python solution for 0268 - Missing Number.

---

solutions/1800-1899/1851-minimum-interval-to-include-each-query-hard.md

- 1851-minimum-interval-to-include-each-query-hard.md created
- 1 approach Approach 1: Heap / Sorting created
- 1 solution using python.

1851, 1 approach, 1 solution

---

solutions/0200-0299/0283-move-zeroes-easy.md

The purpose of this PR is to add coding solution in C++ for the LeetCode [Move Zeroes](https://leetcode.com/problems/move-zeroes/) problem.

Added C++ solution for 0283 - Move Zeroes.

---

solutions/0200-0299/0283-move-zeroes-easy.md

The purpose of this PR is to add coding solution in Java Script for the LeetCode [Move Zeroes](https://leetcode.com/problems/move-zeroes/) problem.

Added JS solution for 0283 - Move Zeroes.

---

solutions/0000-0099/0073-set-matrix-zeroes-medium.md

- 0073-set-matrix-zeroes-medium.md created
- 1 approach, Approach 1: Inplace, Constant Space, Iteration
- 1 solution using python.

0073 created, 1 approach, 1 solution

---

solutions/0300-0399/0367-valid-perfect-square-easy.md

The purpose of this PR is to add coding solution in JS for the LeetCode [Valid Perfect Square](https://leetcode.com/problems/valid-perfect-square/) problem.

Added Python solution for 0367 - Valid Perfect Square.

---

solutions/0300-0399/0367-valid-perfect-square-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Valid Perfect Square](https://leetcode.com/problems/valid-perfect-square/) problem.

Added JS solution for 0367 - Valid Perfect Square.

---

solutions/0300-0399/0374-guess-number-higher-or-lower-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Guess Number Higher or Lower](https://leetcode.com/problems/guess-number-higher-or-lower/) problem.

Added Python solution for 0374 - Guess Number Higher or Lower.

---

solutions/0300-0399/0374-guess-number-higher-or-lower-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Guess Number Higher or Lower](https://leetcode.com/problems/guess-number-higher-or-lower/) problem.

Added JS solution for 0374 - Guess Number Higher or Lower.

---

solutions/0300-0399/0389-find-the-difference-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Find the Difference](https://leetcode.com/problems/find-the-difference/) problem.

Added Python solution for 0389 - Find the Difference.

---

solutions/0200-0299/0202-happy-number-easy.md

- python solution to 0202
- missing tags

0202 python solution

---

solutions/0300-0399/0389-find-the-difference-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Find the Difference](https://leetcode.com/problems/find-the-difference/) problem.

Added JS solution for 0389 - Find the Difference.

---

solutions/0400-0499/0441-arranging-coins-easy.md

The purpose of this PR is to add coding solution in Python for the LeetCode [Arranging Coins](https://leetcode.com/problems/arranging-coins/) problem.

Added Python solution for 0441 - Arranging Coins.

---

solutions/0000-0099/0050-pow-x-n-medium.md

- added python solution to 0050
- added tags, tabs, time/space complexity

0050, 1 solution, tags, tabs

---

solutions/1000-1099/1019-next-greater-node-in-linked-list.md

Added the Cpp solution for  the leetcode problem -  [Next Greater  Node  in Linked List ](https://leetcode.com/problems/next-greater-node-in-linked-list/)

solutions: 1019 - Next Greater Node  in linked list

---

solutions/0400-0499/0441-arranging-coins-easy.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Arranging Coins](https://leetcode.com/problems/arranging-coins/) problem.

Added JS solution for 0441 - Arranging Coins.

---

solutions/0100-0199/0154-find-minimum-in-rotated-sorted-array-ii-hard.md

solutions: 0154 - Find Minimum In Rotated Sorted Array II

---

solutions/0500-0599/0518-coin-change-2-medium.md

The purpose of this PR is to add coding solution in JavaScript for the LeetCode [Coin Change 2](https://leetcode.com/problems/coin-change-ii/) problem.

Added JS solution for 0518 - Coin Change 2.

---

solutions/2000-2099/2013-detect-squares-medium.md

- 2013-detect-squares-medium.md created
- 1 approach, Approach 1: Checking for Diagonal Points created
- 1 solution

2013 created, 1 approach, 1 solution

---

solutions/0100-0199/0162-find-peak-element-medium.md

solutions: 0162-Find Peak Element

---

solutions/1200-1299/1299-replace-elements-with-greatest-element-on-right-side-easy.md

- 1299-replace-elements-with-greatest-element-on-right-side-easy.md created
- 1 approach, Approach 1: Iterate Backwards created
- 1 solution with python

1299 created, 1 approach, 1 solution

---

solutions/0100-0199/0118-pascals-triangle-easy.md

- 0118-pascals-triangle-easy.md created
- 1 approach, Approach 1: Iterative Dynamic Programming Create

0118 created, 1 approach, 1 solution

---

solutions/0000-0099/0027-remove-element-easy.md

- 0027-remove-element-easy.md created
- 1 approach, Approach 1: Two Pointers created

0027 created, 1 approach, 1 solution

---

templates/binary-search.md

add Java binary search template

feat(templates): add Java binary search template

---

templates/two-pointers.md

Java two pointers template

---

templates/linked-list.md

Add Java Linked List template

---

tutorials/math/matrix-exponentiation.md

Resolves #77 
Tutorial for Matrix Exponentiation added. All problems used are available on leetcode.

Matrix Exponentiation Tutorial Added

---

tutorials/math/number-theory/binary-exponentiation.md

The piecewise function image wasn't looking good in dark mode as the image has black text and background was also dark.
It has been changed with latex. No Code changes or links are added. Screenshots are attached.
<details>
<summary> Old </summary
</details>
<details>
<summary> New </summary>
</details>

Piece-wise function image replaced with latex in Binary Exponentiation

---

tutorials/graph-theory/binary-search-tree.md

Wrote tutorial for Binary Search Trees. Closes issue #62 
Please do let me know if i missed something or got something wrong. Thanks!

Tutorial Entry - Binary Search Tree

---

solutions/0200-0299/0263-ugly-number-easy.md
solutions/0600-0699/0650-two-keys-keyboard-medium.md
solutions/2700-2799/2709-greatest-common-divisor-traversal-hard.md
tutorials/math/prime-factors.md

Prime-Factor tutorial and it's suggsted problem solution

---

solutions/1000-1099/1071-greatest-common-divisor-of-strings-easy.md

Solution - [1071](https://leetcode.com/problems/greatest-common-divisor-of-strings)

solutions: 1071 - Greatest Common Divisor of Strings

---

solutions/0600-0699/0605-can-place-flowers-easy.md

Solution - [0605 - Can Place flowers (Easy)](https://leetcode.com/problems/can-place-flowers/)

solutions: 0605 - Can Place flowers (Easy)

---

solutions/1300-1399/1356-sort-integers-by-the-number-of-1-bits-easy.md

Solution - [1356 - Sort Integers by the number of 1 bits](https://leetcode.com/problems/sort-integers-by-the-number-of-1-bits)

solutions: 1356 - Sort Integers by the number of 1 bits

---

solutions/2400-2499/2433-find-the-original-array-of-prefix-xor-medium.md

Solution - [2433 Find the Original Array of prefix XOR](https://leetcode.com/problems/find-the-original-array-of-prefix-xor/)

solutions: 2433 - Find the original array of prefix xor

---

solutions/0500-0599/0501-find-mode-in-binary-search-tree-easy.md

[0501 - Find Mode in Binary Search Tree](https://leetcode.com/problems/find-mode-in-binary-search-tree/)

solutions: 0501 - Find Mode in Binary Search Tree

---

solutions/0300-0399/0334-increasing-triplet-subsequence-medium.md

Solution: [0334 - Increasing Triplet Subsequence](https://leetcode.com/problems/increasing-triplet-subsequence)

solutions: 0334 - Increasing Triplet Subsequence

---

solutions/0400-0499/0443-string-compression-medium.md

Solution: [0443 - String Compression (Medium)](https://leetcode.com/problems/string-compression)

solutions: 0443 - String Compression (Medium)

---

solutions/1600-1699/1679-max-number-of-k-sum-pairs-medium.md

Solution: [1679 - Max Number of K-Sum Pairs](https://leetcode.com/problems/max-number-of-k-sum-pairs/)

solutions: 1679 - Max Number of K-Sum Pairs

---

solutions/0400-0499/0437-path-sum-iii-medium.md

- [] I've applied LaTex for all variables, formulas and time / space complexity instead of using backticks

solutions: 437 - Path Sum III (Medium)

---

solutions/0600-0699/0606-construct-string-from-binary-tree-easy.md

solutions: 0606 - Construct String from Binary Tree (Easy)[Java]

---

solutions/0100-0199/0130-surrounded-regions-medium.md

solutions: 130 - Surrounded Regions (Medium) - DFS

---

tutorials/basic-topics/arrays.md

Found a spelling mismatch issue in the Arrays basic overview section.
Original: min(scores_of_students): returns the highest score in the array, which is 67 in this case
Updated: min(scores_of_students): returns the lowest score in the array, which is 67 in this case

Fixed Spelling mistake for min function

---

tutorials/math/matrix-exponentiation.md

Update matrix-exponentiation.md for fix issue

---

tutorials/graph-theory/disjoint-set-union.md

fix(tutorials): syntax in dsu page

---

tutorials/graph-theory/breadth-first-search.md

typo of variable name corrected

Update breadth-first-search.md typo correction

---

roadmap/index.md

Fixed typo for 'different' and added changes to the grammar.

Fix typo and structure in roadmap/index.md

---

tutorials/basic-topics/sorting/introduction.md

Fix: The incorrect Problem number from 0921 to 0912

Fix: The Problem Number is 0912 not 0921
